apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2020-09-15T14:48:42Z"
  generation: 1
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:singular: {}
        f:conditions: {}
    manager: kube-apiserver
    operation: Update
    time: "2020-09-15T14:48:42Z"
  - apiVersion: apiextensions.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:singular: {}
        f:preserveUnknownFields: {}
        f:scope: {}
        f:version: {}
        f:versions: {}
      f:status:
        f:storedVersions: {}
    manager: subctl
    operation: Update
    time: "2020-09-15T14:48:42Z"
  name: serviceimports.lighthouse.submariner.io
  resourceVersion: "54690"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/serviceimports.lighthouse.submariner.io
  uid: 5ba6df96-65d6-4a66-a126-d921c2a63dd2
spec:
  conversion:
    strategy: None
  group: lighthouse.submariner.io
  names:
    kind: ServiceImport
    listKind: ServiceImportList
    plural: serviceimports
    singular: serviceimport
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v2alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ServiceImport
    listKind: ServiceImportList
    plural: serviceimports
    singular: serviceimport
  conditions:
  - lastTransitionTime: "2020-09-15T14:48:42Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2020-09-15T14:48:42Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v2alpha1
