apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-cluster2-submariner-k8s-broker-cluster
  namespace: submariner-k8s-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: submariner-k8s-broker-cluster
subjects:
- kind: ServiceAccount
  name: cluster-cluster2
  namespace: submariner-k8s-broker 