apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: endpoints.submariner.io
spec:
  group: submariner.io
  names:
    kind: Endpoint
    listKind: EndpointList
    plural: endpoints
    singular: endpoint
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
