apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2020-09-16T12:16:15Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:rules: {}
    manager: subctl
    operation: Update
    time: "2020-09-16T12:20:23Z"
  name: submariner-operator
  resourceVersion: "1931"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/submariner-operator
  uid: 4b702599-7fe7-4279-a06f-d75df5e91cba
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - dnses
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - network.openshift.io
  resources:
  - clusternetworks
  verbs:
  - get
  - list
