apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-09-15T14:48:50Z"
  generation: 1
  labels:
    app: submariner-lighthouse-agent
    component: submariner-lighthouse
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:component: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:app: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:component: {}
          f:spec:
            f:containers:
              k:{"name":"submariner-lighthouse-agent"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"BROKER_K8S_APISERVER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"BROKER_K8S_APISERVERTOKEN"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"BROKER_K8S_CA"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"BROKER_K8S_REMOTENAMESPACE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SUBMARINER_CLUSTERID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SUBMARINER_DEBUG"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SUBMARINER_EXCLUDENS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SUBMARINER_GLOBALNET_ENABLED"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SUBMARINER_NAMESPACE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
    manager: submariner-operator
    operation: Update
    time: "2020-09-15T14:48:50Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-15T14:48:57Z"
  name: submariner-lighthouse-agent
  namespace: submariner-operator
  resourceVersion: "54869"
  selfLink: /apis/apps/v1/namespaces/submariner-operator/deployments/submariner-lighthouse-agent
  uid: da038fd6-49f7-4ecf-b684-35de48dcec17
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: submariner-lighthouse-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: submariner-lighthouse-agent
        component: submariner-lighthouse
    spec:
      containers:
      - env:
        - name: SUBMARINER_NAMESPACE
          value: submariner-operator
        - name: SUBMARINER_CLUSTERID
          value: test2
        - name: SUBMARINER_EXCLUDENS
          value: submariner,kube-system,operators
        - name: SUBMARINER_DEBUG
          value: "false"
        - name: SUBMARINER_GLOBALNET_ENABLED
          value: "false"
        - name: BROKER_K8S_APISERVER
          value: 10.0.118.46:35613
        - name: BROKER_K8S_APISERVERTOKEN
          value: eyJhbGciOiJSUzI1NiIsImtpZCI6IlFyZUpTODFUYk1YTWlfaVZpN3dpdGs5OTBmWlNuaWFrMjRMcll5TUR6elkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdWJtYXJpbmVyLWs4cy1icm9rZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiY2x1c3Rlci10ZXN0Mi10b2tlbi1teHhzcCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjbHVzdGVyLXRlc3QyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZmE3MjczNzctNDI0MS00YmFkLWE2NzAtZjk1N2NlMDI3MjczIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnN1Ym1hcmluZXItazhzLWJyb2tlcjpjbHVzdGVyLXRlc3QyIn0.vgJmxxXAaaK__zQOcb7koFitXG5_ew8s3v-6QMM_EVc0XoGczXncbRKb0HYMamy-H3IbrIc1upFEt9uz3d3HfzvgoLJqd72uYgAhk-4MvPbeeEc9u7CfrHn5GYEtmv1r9UObrTg2eOLYOt5oCQ70iZFHbN9PblhLHEvjh9gX6ZLsPshnmB8s1EEFxH4qxPLbW4GFGMorvu8_C779IS0viCtW73axB-CRSYX2HYhyBbc3OjErTOW6E9uD6jcX4ewwAuH1LjQs2IQMp0PeaBA41isFNUEQOBG__oLmCfRbyK-6ibf1ceUGy2hkurDTBK6B8EaVYXWf3gf0i2NmIRZFaA
        - name: BROKER_K8S_REMOTENAMESPACE
          value: submariner-k8s-broker
        - name: BROKER_K8S_CA
          value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01Ea3hOVEE1TXpNME5Gb1hEVE13TURreE16QTVNek0wTkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTYyCnRvTkQ2TVdMWCsxRjh3Szc3Z2lDU3RsckdBSEdkd05qNlRZSlhwRzA1MHBIOFovQUZsYkowem0xRnM0dTZLY3YKOWhHZ3dJYTQ0clN2dkN6NVJJT2ZNWFBhaHVKendjd25icExXcEd0OStDS096QmZTUkpibHJoY25vQWVQbG83UgpudDBVOGVRbWJLcS8zQS8yMkFGMmtNeGM4Rkl5L0JKU1ptL21TcjFLTUFtM3hhWDFmYXMxYVdPY25ObmVLd3F1CllFMjJxUGo3Ynk1TzR1THllYlQzckVRTzNKQUx0My9WZkZXWlJhOFhuT1ZpTFNXajBia0dLZlZuMFdBSVJ0LzQKUUNoT1huUG1uNmVHbGt4QWhtVlpjOS9ScVJSUVh1c0VBb2RkYUZqcDljMk5mcjFVMy9KS0xBWGZsT0drUG4xZgpvd0Q2V3QrNTFkemlSYkJBeDBrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFRk5ESTlLRUhCcWVFRTdNTE0rd3lUQTBJVi8KUzVkdnp6bVNvVWdNRTRSZ2NQOHJUTWw0RGVXVFFybVBmRXpiY0VRdUs0b1pDYXViY3d1eCtndldZL05RTEwvTgppdVB6ZFNuM1UxQ1o2N3U3NFJIL3VSWGxyNFM3bVZhSThwSW5xeDFPVGtsamxIYkxqdUVReTF2S3JiR25vZHNUClpqR1pkc2NjdlFFZGFWVmh5bElkNXJrVUw2cGV2aFF4QzFnREtSdWJROWhRM1RkV0RtVmJtNktPQzV6QS9XRzgKR3dhbnZRY2gvUmRZRTllMDUwTEc5V3pXTEFtY2VZejd4MkFKQTBWMGtLcUFCNlF4SVNoM0lVbGhZVVhFWnRPTgpVRU1WK28rTFJDNHpMNmFKeHJiRlgrdExpVjBvY0xSMHl3VGt0eTBISURCYXRwbGsyc2k0cUhXOVJIUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        image: quay.io/submariner/lighthouse-agent:0.6.1
        imagePullPolicy: IfNotPresent
        name: submariner-lighthouse-agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: submariner-lighthouse
      serviceAccountName: submariner-lighthouse
      terminationGracePeriodSeconds: 0
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-09-15T14:48:57Z"
    lastUpdateTime: "2020-09-15T14:48:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-09-15T14:48:50Z"
    lastUpdateTime: "2020-09-15T14:48:57Z"
    message: ReplicaSet "submariner-lighthouse-agent-6dcfff6d47" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
