apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2020-09-16T12:16:15Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:roleRef:
        f:apiGroup: {}
        f:kind: {}
        f:name: {}
      f:subjects: {}
    manager: kubectl
    operation: Update
    time: "2020-09-16T12:16:15Z"
  name: submariner-lighthouse
  resourceVersion: "1950"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/submariner-lighthouse
  uid: 8407eb48-8ade-4fcb-84d5-bfbfce3dc923
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: submariner-lighthouse
subjects:
- kind: ServiceAccount
  name: submariner-lighthouse
  namespace: submariner-operator
