apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2020-09-16T12:16:15Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:rules: {}
    manager: kubectl
    operation: Update
    time: "2020-09-16T12:16:15Z"
  name: submariner-operator:globalnet
  resourceVersion: "1930"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/submariner-operator%3Aglobalnet
  uid: afde8761-2d4f-4e34-bac5-c1db94c63e53
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - submariner.io
  resources:
  - endpoints
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lighthouse.submariner.io
  resources:
  - serviceexports
  verbs:
  - get
  - list
  - watch
