apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gateways.submariner.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: submariner.io
  version: v1
  names:
    kind: Gateway
    listKind: GatewayList
    plural: gateways
    singular: gateway
  scope: Namespaced
  additionalPrinterColumns:
    - name: ha-status
      type: string
      description: High Availability Status of the Gateway
      JSONPath: .status.haStatus
