apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: submariner-k8s-broker-admin-submariner-k8s-broker-admin
  namespace: submariner-k8s-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: submariner-k8s-broker-admin
subjects:
- kind: ServiceAccount
  name: submariner-k8s-broker-admin
  namespace: submariner-k8s-broker
