apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: submariner-k8s-broker-admin
  namespace: submariner-k8s-broker
rules:
- apiGroups:
  - submariner.io
  resources:
  - clusters
  - endpoints
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - secrets
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - get
  - list
  - delete
- apiGroups:
  - lighthouse.submariner.io
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - update
  - delete
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - update
  - delete
